export interface OnboardingQuestion {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  selectionType: 'single' | 'multi';
  options: {
    id: string;
    label: string;
    icon: string;
  }[];
}

export interface VerticalPreset {
  name: string;
  category: string;
  defaultTagline: string;
  defaultPrimaryColor: string;
  defaultSecondaryColor: string;
  heroImageUrl: string;
  bannerImages: string[];
  onboardingQuestions: OnboardingQuestion[];
}

export interface BrandKitConfig {
  brandName: string;
  tagline: string;
  primaryColor: string;
  secondaryColor: string;
  logoUrl: string;
  vertical: string;
  customQuestions?: OnboardingQuestion[];
}

export const VERTICAL_PRESETS: Record<string, VerticalPreset> = {
  // RETAIL - HOME IMPROVEMENT
  'retail-home-improvement': {
    name: 'Home Improvement',
    category: 'Retail',
    defaultTagline: 'DO-ER',
    defaultPrimaryColor: '#f97316',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800',
      'https://images.unsplash.com/photo-1585128903994-2a69a3d6e7e8?w=800',
      'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800',
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'home-type',
        title: 'What type of home do you have?',
        subtitle: 'Help us personalize your experience',
        icon: 'Home',
        selectionType: 'single',
        options: [
          { id: 'single-family', label: 'Single Family', icon: 'Home' },
          { id: 'apartment', label: 'Apartment', icon: 'Building' },
          { id: 'townhouse', label: 'Townhouse', icon: 'Building2' },
          { id: 'condo', label: 'Condo', icon: 'Building' },
        ],
      },
      {
        id: 'projects',
        title: 'What projects are you working on?',
        subtitle: 'Select all that apply',
        icon: 'Wrench',
        selectionType: 'multi',
        options: [
          { id: 'kitchen', label: 'Kitchen', icon: 'UtensilsCrossed' },
          { id: 'bathroom', label: 'Bathroom', icon: 'Droplet' },
          { id: 'living-room', label: 'Living Room', icon: 'Sofa' },
          { id: 'bedroom', label: 'Bedroom', icon: 'Bed' },
          { id: 'outdoor', label: 'Outdoor', icon: 'Trees' },
          { id: 'garage', label: 'Garage', icon: 'Car' },
          { id: 'painting', label: 'Painting', icon: 'Paintbrush' },
          { id: 'general', label: 'General', icon: 'Wrench' },
        ],
      },
      {
        id: 'savings',
        title: 'Where do you want to save?',
        subtitle: 'Select your favorite categories',
        icon: 'Tag',
        selectionType: 'multi',
        options: [
          { id: 'power-tools', label: 'Power Tools', icon: 'Drill' },
          { id: 'garden-center', label: 'Garden Center', icon: 'Flower' },
          { id: 'outdoor-power', label: 'Outdoor Power', icon: 'Wind' },
          { id: 'building-materials', label: 'Building Materials', icon: 'Package' },
          { id: 'paint', label: 'Paint', icon: 'Palette' },
          { id: 'lighting', label: 'Lighting', icon: 'Lightbulb' },
        ],
      },
    ],
  },

  // RETAIL - FASHION
  'retail-fashion-apparel': {
    name: 'Fashion & Apparel',
    category: 'Retail',
    defaultTagline: 'Style Your Way',
    defaultPrimaryColor: '#000000',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800',
      'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800',
      'https://images.unsplash.com/photo-1558769132-cb1aea3c9565?w=800',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'style',
        title: "What's your style?",
        subtitle: 'Choose your fashion identity',
        icon: 'Shirt',
        selectionType: 'multi',
        options: [
          { id: 'casual', label: 'Casual', icon: 'Shirt' },
          { id: 'formal', label: 'Formal', icon: 'Briefcase' },
          { id: 'athleisure', label: 'Athleisure', icon: 'Dumbbell' },
          { id: 'streetwear', label: 'Streetwear', icon: 'Sparkles' },
          { id: 'minimalist', label: 'Minimalist', icon: 'Minus' },
          { id: 'bohemian', label: 'Bohemian', icon: 'Flower2' },
        ],
      },
      {
        id: 'shopping-for',
        title: 'What are you shopping for?',
        subtitle: 'Select all that apply',
        icon: 'ShoppingBag',
        selectionType: 'multi',
        options: [
          { id: 'tops', label: 'Tops', icon: 'Shirt' },
          { id: 'bottoms', label: 'Bottoms', icon: 'Scissors' },
          { id: 'dresses', label: 'Dresses', icon: 'Sparkles' },
          { id: 'shoes', label: 'Shoes', icon: 'FootprintsIcon' },
          { id: 'accessories', label: 'Accessories', icon: 'Watch' },
          { id: 'outerwear', label: 'Outerwear', icon: 'Cloud' },
        ],
      },
      {
        id: 'fit-preference',
        title: "What's your preferred fit?",
        subtitle: 'How do you like your clothes to fit?',
        icon: 'Ruler',
        selectionType: 'single',
        options: [
          { id: 'slim', label: 'Slim Fit', icon: 'Minimize2' },
          { id: 'regular', label: 'Regular Fit', icon: 'Square' },
          { id: 'relaxed', label: 'Relaxed Fit', icon: 'Maximize2' },
          { id: 'oversized', label: 'Oversized', icon: 'Maximize' },
        ],
      },
    ],
  },

  // RETAIL - GROCERY
  'retail-grocery': {
    name: 'Grocery & Supermarket',
    category: 'Retail',
    defaultTagline: 'Fresh Every Day',
    defaultPrimaryColor: '#22c55e',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
      'https://images.unsplash.com/photo-1573070853701-5b66ae02e77e?w=800',
      'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?w=800',
      'https://images.unsplash.com/photo-1601599561213-832382fd07ba?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'dietary',
        title: 'Any dietary preferences?',
        subtitle: 'We\'ll personalize your recommendations',
        icon: 'Apple',
        selectionType: 'multi',
        options: [
          { id: 'vegetarian', label: 'Vegetarian', icon: 'Leaf' },
          { id: 'vegan', label: 'Vegan', icon: 'Sprout' },
          { id: 'gluten-free', label: 'Gluten-Free', icon: 'Ban' },
          { id: 'keto', label: 'Keto', icon: 'Beef' },
          { id: 'organic', label: 'Organic', icon: 'Flower' },
          { id: 'no-restrictions', label: 'No Restrictions', icon: 'Check' },
        ],
      },
      {
        id: 'shopping-frequency',
        title: 'How often do you shop?',
        subtitle: 'Help us plan your savings',
        icon: 'Calendar',
        selectionType: 'single',
        options: [
          { id: 'daily', label: 'Daily', icon: 'CalendarDays' },
          { id: 'weekly', label: 'Weekly', icon: 'CalendarRange' },
          { id: 'biweekly', label: 'Bi-Weekly', icon: 'Calendar' },
          { id: 'monthly', label: 'Monthly', icon: 'CalendarCheck' },
        ],
      },
      {
        id: 'categories',
        title: 'What do you buy most?',
        subtitle: 'Select your top categories',
        icon: 'ShoppingCart',
        selectionType: 'multi',
        options: [
          { id: 'produce', label: 'Produce', icon: 'Apple' },
          { id: 'meat', label: 'Meat & Seafood', icon: 'Beef' },
          { id: 'dairy', label: 'Dairy', icon: 'Milk' },
          { id: 'bakery', label: 'Bakery', icon: 'Cookie' },
          { id: 'beverages', label: 'Beverages', icon: 'Coffee' },
          { id: 'snacks', label: 'Snacks', icon: 'Candy' },
        ],
      },
    ],
  },

  // RETAIL - ELECTRONICS
  'retail-electronics': {
    name: 'Electronics & Tech',
    category: 'Retail',
    defaultTagline: 'Tech Made Simple',
    defaultPrimaryColor: '#3b82f6',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
      'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'tech-interest',
        title: "What tech are you interested in?",
        subtitle: 'Select your categories',
        icon: 'Laptop',
        selectionType: 'multi',
        options: [
          { id: 'computers', label: 'Computers', icon: 'Monitor' },
          { id: 'smartphones', label: 'Smartphones', icon: 'Smartphone' },
          { id: 'gaming', label: 'Gaming', icon: 'Gamepad2' },
          { id: 'audio', label: 'Audio', icon: 'Headphones' },
          { id: 'smart-home', label: 'Smart Home', icon: 'Home' },
          { id: 'wearables', label: 'Wearables', icon: 'Watch' },
        ],
      },
      {
        id: 'usage',
        title: 'How will you use it?',
        subtitle: 'Tell us your primary use case',
        icon: 'Target',
        selectionType: 'multi',
        options: [
          { id: 'work', label: 'Work', icon: 'Briefcase' },
          { id: 'gaming', label: 'Gaming', icon: 'Gamepad' },
          { id: 'creativity', label: 'Creativity', icon: 'Palette' },
          { id: 'entertainment', label: 'Entertainment', icon: 'Film' },
          { id: 'productivity', label: 'Productivity', icon: 'CheckSquare' },
          { id: 'education', label: 'Education', icon: 'GraduationCap' },
        ],
      },
      {
        id: 'budget',
        title: "What's your budget range?",
        subtitle: 'We\'ll show you the best options',
        icon: 'DollarSign',
        selectionType: 'single',
        options: [
          { id: 'budget', label: 'Budget ($0-$500)', icon: 'Tag' },
          { id: 'mid-range', label: 'Mid-Range ($500-$1500)', icon: 'Tags' },
          { id: 'premium', label: 'Premium ($1500-$3000)', icon: 'Award' },
          { id: 'luxury', label: 'Luxury ($3000+)', icon: 'Crown' },
        ],
      },
    ],
  },

  // FITNESS - GYM
  'fitness-gym': {
    name: 'Gym & Fitness Center',
    category: 'Fitness',
    defaultTagline: 'Transform Your Body',
    defaultPrimaryColor: '#ef4444',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800',
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800',
      'https://images.unsplash.com/photo-1584466977773-e625c37cdd50?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'fitness-level',
        title: "What's your fitness level?",
        subtitle: 'Be honest - we\'ll meet you where you are',
        icon: 'Activity',
        selectionType: 'single',
        options: [
          { id: 'beginner', label: 'Beginner', icon: 'TrendingUp' },
          { id: 'intermediate', label: 'Intermediate', icon: 'BarChart' },
          { id: 'advanced', label: 'Advanced', icon: 'Activity' },
          { id: 'expert', label: 'Expert', icon: 'Zap' },
        ],
      },
      {
        id: 'goals',
        title: "What are your fitness goals?",
        subtitle: 'Select all that apply',
        icon: 'Target',
        selectionType: 'multi',
        options: [
          { id: 'weight-loss', label: 'Weight Loss', icon: 'TrendingDown' },
          { id: 'muscle-gain', label: 'Muscle Gain', icon: 'Dumbbell' },
          { id: 'endurance', label: 'Endurance', icon: 'Heart' },
          { id: 'flexibility', label: 'Flexibility', icon: 'Move' },
          { id: 'strength', label: 'Strength', icon: 'Zap' },
          { id: 'general-health', label: 'General Health', icon: 'HeartPulse' },
        ],
      },
      {
        id: 'equipment',
        title: 'What equipment do you prefer?',
        subtitle: 'Choose your training style',
        icon: 'Dumbbell',
        selectionType: 'multi',
        options: [
          { id: 'free-weights', label: 'Free Weights', icon: 'Dumbbell' },
          { id: 'machines', label: 'Machines', icon: 'Settings' },
          { id: 'cardio', label: 'Cardio', icon: 'Activity' },
          { id: 'bodyweight', label: 'Bodyweight', icon: 'User' },
          { id: 'classes', label: 'Classes', icon: 'Users' },
          { id: 'personal-training', label: 'Personal Training', icon: 'UserCheck' },
        ],
      },
    ],
  },

  // FITNESS - YOGA
  'fitness-yoga': {
    name: 'Yoga Studio',
    category: 'Fitness',
    defaultTagline: 'Find Your Balance',
    defaultPrimaryColor: '#8b5cf6',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
      'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800',
      'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'experience',
        title: "What's your yoga experience?",
        subtitle: 'Help us find the right classes for you',
        icon: 'Sparkles',
        selectionType: 'single',
        options: [
          { id: 'new', label: 'Brand New', icon: 'Baby' },
          { id: 'beginner', label: 'Beginner', icon: 'Sprout' },
          { id: 'intermediate', label: 'Intermediate', icon: 'Flower' },
          { id: 'advanced', label: 'Advanced', icon: 'TreePine' },
        ],
      },
      {
        id: 'style',
        title: 'What styles interest you?',
        subtitle: 'Select all you want to explore',
        icon: 'Heart',
        selectionType: 'multi',
        options: [
          { id: 'hatha', label: 'Hatha', icon: 'CircleDot' },
          { id: 'vinyasa', label: 'Vinyasa', icon: 'Waves' },
          { id: 'yin', label: 'Yin', icon: 'Moon' },
          { id: 'hot-yoga', label: 'Hot Yoga', icon: 'Flame' },
          { id: 'restorative', label: 'Restorative', icon: 'CloudRain' },
          { id: 'power', label: 'Power Yoga', icon: 'Zap' },
        ],
      },
      {
        id: 'goals',
        title: 'What brings you to yoga?',
        subtitle: 'Your wellness goals',
        icon: 'Target',
        selectionType: 'multi',
        options: [
          { id: 'flexibility', label: 'Flexibility', icon: 'Move' },
          { id: 'stress-relief', label: 'Stress Relief', icon: 'Smile' },
          { id: 'strength', label: 'Strength', icon: 'Dumbbell' },
          { id: 'mindfulness', label: 'Mindfulness', icon: 'Brain' },
          { id: 'community', label: 'Community', icon: 'Users' },
          { id: 'overall-health', label: 'Overall Health', icon: 'Heart' },
        ],
      },
    ],
  },

  // FOOD - RESTAURANT
  'food-restaurant': {
    name: 'Restaurant',
    category: 'Food & Beverage',
    defaultTagline: 'Taste the Difference',
    defaultPrimaryColor: '#dc2626',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
      'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'dining-preference',
        title: "What's your dining preference?",
        subtitle: 'How do you like to enjoy our food?',
        icon: 'UtensilsCrossed',
        selectionType: 'multi',
        options: [
          { id: 'dine-in', label: 'Dine-In', icon: 'UtensilsCrossed' },
          { id: 'takeout', label: 'Takeout', icon: 'ShoppingBag' },
          { id: 'delivery', label: 'Delivery', icon: 'Truck' },
          { id: 'catering', label: 'Catering', icon: 'Users' },
        ],
      },
      {
        id: 'cuisines',
        title: 'What cuisines do you love?',
        subtitle: 'Select your favorites',
        icon: 'ChefHat',
        selectionType: 'multi',
        options: [
          { id: 'italian', label: 'Italian', icon: 'Pizza' },
          { id: 'mexican', label: 'Mexican', icon: 'Flame' },
          { id: 'asian', label: 'Asian', icon: 'Coffee' },
          { id: 'american', label: 'American', icon: 'Beef' },
          { id: 'mediterranean', label: 'Mediterranean', icon: 'Leaf' },
          { id: 'seafood', label: 'Seafood', icon: 'Fish' },
        ],
      },
      {
        id: 'dietary',
        title: 'Any dietary preferences?',
        subtitle: 'We\'ll show you the best options',
        icon: 'Apple',
        selectionType: 'multi',
        options: [
          { id: 'vegetarian', label: 'Vegetarian', icon: 'Leaf' },
          { id: 'vegan', label: 'Vegan', icon: 'Sprout' },
          { id: 'gluten-free', label: 'Gluten-Free', icon: 'Ban' },
          { id: 'keto', label: 'Keto', icon: 'Beef' },
          { id: 'halal', label: 'Halal', icon: 'Check' },
          { id: 'no-restrictions', label: 'No Restrictions', icon: 'CheckCheck' },
        ],
      },
    ],
  },

  // FOOD - COFFEE SHOP
  'food-coffee': {
    name: 'Coffee Shop',
    category: 'Food & Beverage',
    defaultTagline: 'Brewed to Perfection',
    defaultPrimaryColor: '#92400e',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
      'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800',
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'coffee-preference',
        title: 'How do you like your coffee?',
        subtitle: 'Tell us your go-to',
        icon: 'Coffee',
        selectionType: 'multi',
        options: [
          { id: 'black', label: 'Black Coffee', icon: 'Coffee' },
          { id: 'espresso', label: 'Espresso', icon: 'Zap' },
          { id: 'latte', label: 'Latte', icon: 'Milk' },
          { id: 'cappuccino', label: 'Cappuccino', icon: 'CloudRain' },
          { id: 'iced', label: 'Iced Coffee', icon: 'Snowflake' },
          { id: 'specialty', label: 'Specialty Drinks', icon: 'Sparkles' },
        ],
      },
      {
        id: 'visit-time',
        title: 'When do you usually visit?',
        subtitle: 'Help us prepare for you',
        icon: 'Clock',
        selectionType: 'multi',
        options: [
          { id: 'morning', label: 'Morning (6-9am)', icon: 'Sunrise' },
          { id: 'mid-morning', label: 'Mid-Morning (9-12pm)', icon: 'Sun' },
          { id: 'afternoon', label: 'Afternoon (12-5pm)', icon: 'CloudSun' },
          { id: 'evening', label: 'Evening (5-8pm)', icon: 'Sunset' },
        ],
      },
      {
        id: 'add-ons',
        title: 'What else do you enjoy?',
        subtitle: 'Beyond coffee',
        icon: 'Cookie',
        selectionType: 'multi',
        options: [
          { id: 'pastries', label: 'Pastries', icon: 'Cookie' },
          { id: 'sandwiches', label: 'Sandwiches', icon: 'Sandwich' },
          { id: 'tea', label: 'Tea', icon: 'Leaf' },
          { id: 'smoothies', label: 'Smoothies', icon: 'Apple' },
          { id: 'snacks', label: 'Snacks', icon: 'Candy' },
          { id: 'merchandise', label: 'Merchandise', icon: 'ShoppingBag' },
        ],
      },
    ],
  },

  // TRAVEL - AIRLINE
  'travel-airline': {
    name: 'Airline',
    category: 'Travel',
    defaultTagline: 'Fly With Us',
    defaultPrimaryColor: '#0ea5e9',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800',
      'https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800',
      'https://images.unsplash.com/photo-1583899235660-cb32a2f2d909?w=800',
      'https://images.unsplash.com/photo-1569629743817-70d8db6c323b?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'travel-frequency',
        title: 'How often do you fly?',
        subtitle: 'Help us serve you better',
        icon: 'Plane',
        selectionType: 'single',
        options: [
          { id: 'weekly', label: 'Weekly', icon: 'CalendarDays' },
          { id: 'monthly', label: 'Monthly', icon: 'Calendar' },
          { id: 'few-times-year', label: 'Few Times a Year', icon: 'CalendarRange' },
          { id: 'rarely', label: 'Rarely', icon: 'CalendarCheck' },
        ],
      },
      {
        id: 'travel-purpose',
        title: 'Why do you travel?',
        subtitle: 'Select all that apply',
        icon: 'Briefcase',
        selectionType: 'multi',
        options: [
          { id: 'business', label: 'Business', icon: 'Briefcase' },
          { id: 'leisure', label: 'Leisure', icon: 'Palmtree' },
          { id: 'family', label: 'Family Visits', icon: 'Users' },
          { id: 'adventure', label: 'Adventure', icon: 'Mountain' },
          { id: 'events', label: 'Events', icon: 'PartyPopper' },
          { id: 'education', label: 'Education', icon: 'GraduationCap' },
        ],
      },
      {
        id: 'preferences',
        title: 'What matters most to you?',
        subtitle: 'Your travel priorities',
        icon: 'Star',
        selectionType: 'multi',
        options: [
          { id: 'price', label: 'Best Price', icon: 'DollarSign' },
          { id: 'comfort', label: 'Comfort', icon: 'Armchair' },
          { id: 'schedule', label: 'Schedule Flexibility', icon: 'Clock' },
          { id: 'rewards', label: 'Rewards Program', icon: 'Award' },
          { id: 'direct-flights', label: 'Direct Flights', icon: 'MoveRight' },
          { id: 'premium', label: 'Premium Experience', icon: 'Crown' },
        ],
      },
    ],
  },

  // TRAVEL - HOTEL
  'travel-hotel': {
    name: 'Hotel',
    category: 'Travel',
    defaultTagline: 'Your Home Away From Home',
    defaultPrimaryColor: '#a855f7',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'travel-type',
        title: 'What type of traveler are you?',
        subtitle: 'Help us personalize your stay',
        icon: 'Luggage',
        selectionType: 'multi',
        options: [
          { id: 'business', label: 'Business', icon: 'Briefcase' },
          { id: 'leisure', label: 'Leisure', icon: 'Palmtree' },
          { id: 'family', label: 'Family', icon: 'Baby' },
          { id: 'couples', label: 'Couples', icon: 'Heart' },
          { id: 'solo', label: 'Solo', icon: 'User' },
          { id: 'group', label: 'Group', icon: 'Users' },
        ],
      },
      {
        id: 'amenities',
        title: 'Which amenities are important?',
        subtitle: 'Select all you value',
        icon: 'Sparkles',
        selectionType: 'multi',
        options: [
          { id: 'wifi', label: 'Free WiFi', icon: 'Wifi' },
          { id: 'breakfast', label: 'Breakfast', icon: 'Coffee' },
          { id: 'pool', label: 'Pool', icon: 'Waves' },
          { id: 'gym', label: 'Gym', icon: 'Dumbbell' },
          { id: 'parking', label: 'Parking', icon: 'Car' },
          { id: 'spa', label: 'Spa', icon: 'Flower2' },
        ],
      },
      {
        id: 'room-preference',
        title: 'What room features do you prefer?',
        subtitle: 'Make your stay perfect',
        icon: 'Bed',
        selectionType: 'multi',
        options: [
          { id: 'view', label: 'Great View', icon: 'Mountain' },
          { id: 'balcony', label: 'Balcony', icon: 'DoorOpen' },
          { id: 'suite', label: 'Suite', icon: 'Home' },
          { id: 'kitchenette', label: 'Kitchenette', icon: 'UtensilsCrossed' },
          { id: 'quiet', label: 'Quiet Location', icon: 'Volume' },
          { id: 'accessible', label: 'Accessible', icon: 'Accessibility' },
        ],
      },
    ],
  },

  // TRAVEL - CRUISE
  'travel-cruise': {
    name: 'Cruise Line',
    category: 'Travel',
    defaultTagline: 'Set Sail to Adventure',
    defaultPrimaryColor: '#0891b2',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1545242527-2881e1c7c9f1?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1545242527-2881e1c7c9f1?w=800',
      'https://images.unsplash.com/photo-1511120974689-e61f8d75a57b?w=800',
      'https://images.unsplash.com/photo-1573736323988-c9dd85069684?w=800',
      'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'cruise-experience',
        title: 'Cruise experience level?',
        subtitle: 'Have you cruised before?',
        icon: 'Ship',
        selectionType: 'single',
        options: [
          { id: 'first-time', label: 'First Timer', icon: 'Sparkles' },
          { id: '2-5-cruises', label: '2-5 Cruises', icon: 'Anchor' },
          { id: '6-10-cruises', label: '6-10 Cruises', icon: 'Waves' },
          { id: 'cruise-veteran', label: 'Cruise Veteran', icon: 'Ship' },
        ],
      },
      {
        id: 'destinations',
        title: 'Where do you want to sail?',
        subtitle: 'Select your dream destinations',
        icon: 'MapPin',
        selectionType: 'multi',
        options: [
          { id: 'caribbean', label: 'Caribbean', icon: 'Palmtree' },
          { id: 'mediterranean', label: 'Mediterranean', icon: 'Sun' },
          { id: 'alaska', label: 'Alaska', icon: 'Snowflake' },
          { id: 'asia', label: 'Asia', icon: 'Globe' },
          { id: 'northern-europe', label: 'Northern Europe', icon: 'CloudRain' },
          { id: 'south-pacific', label: 'South Pacific', icon: 'Waves' },
        ],
      },
      {
        id: 'activities',
        title: 'What activities interest you?',
        subtitle: 'Onboard and excursions',
        icon: 'Activity',
        selectionType: 'multi',
        options: [
          { id: 'dining', label: 'Fine Dining', icon: 'UtensilsCrossed' },
          { id: 'entertainment', label: 'Shows & Entertainment', icon: 'Music' },
          { id: 'spa', label: 'Spa & Wellness', icon: 'Flower2' },
          { id: 'adventure', label: 'Adventure Sports', icon: 'Mountain' },
          { id: 'relaxation', label: 'Relaxation', icon: 'CloudSun' },
          { id: 'culture', label: 'Cultural Excursions', icon: 'Landmark' },
        ],
      },
    ],
  },

  // TRAVEL - CAR RENTAL
  'travel-car-rental': {
    name: 'Car Rental',
    category: 'Travel',
    defaultTagline: 'Drive Your Way',
    defaultPrimaryColor: '#eab308',
    defaultSecondaryColor: '#000000',
    heroImageUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'rental-purpose',
        title: 'Why are you renting?',
        subtitle: 'Help us find the perfect vehicle',
        icon: 'Car',
        selectionType: 'multi',
        options: [
          { id: 'business', label: 'Business Trip', icon: 'Briefcase' },
          { id: 'vacation', label: 'Vacation', icon: 'Palmtree' },
          { id: 'special-occasion', label: 'Special Occasion', icon: 'PartyPopper' },
          { id: 'temporary', label: 'Temporary Need', icon: 'Clock' },
          { id: 'test-drive', label: 'Test Before Buying', icon: 'Key' },
        ],
      },
      {
        id: 'vehicle-type',
        title: 'What type of vehicle do you prefer?',
        subtitle: 'Select all you like',
        icon: 'CarFront',
        selectionType: 'multi',
        options: [
          { id: 'economy', label: 'Economy', icon: 'Tag' },
          { id: 'compact', label: 'Compact', icon: 'Car' },
          { id: 'suv', label: 'SUV', icon: 'Truck' },
          { id: 'luxury', label: 'Luxury', icon: 'Crown' },
          { id: 'van', label: 'Van/Minivan', icon: 'Bus' },
          { id: 'sports', label: 'Sports Car', icon: 'Zap' },
        ],
      },
      {
        id: 'features',
        title: 'Important features?',
        subtitle: 'What do you need?',
        icon: 'Settings',
        selectionType: 'multi',
        options: [
          { id: 'gps', label: 'GPS Navigation', icon: 'Navigation' },
          { id: 'automatic', label: 'Automatic Transmission', icon: 'Settings' },
          { id: 'bluetooth', label: 'Bluetooth', icon: 'Bluetooth' },
          { id: 'backup-camera', label: 'Backup Camera', icon: 'Camera' },
          { id: 'child-seat', label: 'Child Seat', icon: 'Baby' },
          { id: 'unlimited-miles', label: 'Unlimited Miles', icon: 'Infinity' },
        ],
      },
    ],
  },

  // EDUCATION - ONLINE LEARNING
  'education-online-learning': {
    name: 'Online Learning Platform',
    category: 'Education',
    defaultTagline: 'Learn Without Limits',
    defaultPrimaryColor: '#6366f1',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800',
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
      'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=800',
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'skill-level',
        title: "What's your current level?",
        subtitle: 'Be honest - we all start somewhere',
        icon: 'GraduationCap',
        selectionType: 'single',
        options: [
          { id: 'beginner', label: 'Beginner', icon: 'Sprout' },
          { id: 'intermediate', label: 'Intermediate', icon: 'TreePine' },
          { id: 'advanced', label: 'Advanced', icon: 'Mountain' },
          { id: 'expert', label: 'Expert', icon: 'Trophy' },
        ],
      },
      {
        id: 'subjects',
        title: 'What do you want to learn?',
        subtitle: 'Select all that interest you',
        icon: 'BookOpen',
        selectionType: 'multi',
        options: [
          { id: 'programming', label: 'Programming', icon: 'Code' },
          { id: 'design', label: 'Design', icon: 'Palette' },
          { id: 'business', label: 'Business', icon: 'Briefcase' },
          { id: 'marketing', label: 'Marketing', icon: 'TrendingUp' },
          { id: 'languages', label: 'Languages', icon: 'Languages' },
          { id: 'data-science', label: 'Data Science', icon: 'Database' },
          { id: 'personal-development', label: 'Personal Development', icon: 'User' },
          { id: 'photography', label: 'Photography', icon: 'Camera' },
        ],
      },
      {
        id: 'learning-style',
        title: 'How do you prefer to learn?',
        subtitle: 'Choose your style',
        icon: 'Brain',
        selectionType: 'multi',
        options: [
          { id: 'video', label: 'Video Lessons', icon: 'Film' },
          { id: 'reading', label: 'Reading', icon: 'BookOpen' },
          { id: 'interactive', label: 'Interactive', icon: 'Gamepad2' },
          { id: 'live-classes', label: 'Live Classes', icon: 'Video' },
          { id: 'practice', label: 'Hands-on Practice', icon: 'Wrench' },
          { id: 'quizzes', label: 'Quizzes', icon: 'CheckSquare' },
        ],
      },
    ],
  },

  // EDUCATION - UNIVERSITY
  'education-university': {
    name: 'University',
    category: 'Education',
    defaultTagline: 'Where Futures Begin',
    defaultPrimaryColor: '#0c4a6e',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
      'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800',
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
      'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'student-type',
        title: 'What type of student are you?',
        subtitle: 'Tell us about yourself',
        icon: 'User',
        selectionType: 'single',
        options: [
          { id: 'prospective', label: 'Prospective Student', icon: 'Eye' },
          { id: 'current', label: 'Current Student', icon: 'BookOpen' },
          { id: 'graduate', label: 'Graduate Student', icon: 'GraduationCap' },
          { id: 'alumni', label: 'Alumni', icon: 'Award' },
        ],
      },
      {
        id: 'interests',
        title: 'Areas of interest?',
        subtitle: 'Select fields you want to explore',
        icon: 'Compass',
        selectionType: 'multi',
        options: [
          { id: 'stem', label: 'STEM', icon: 'Atom' },
          { id: 'arts', label: 'Arts & Humanities', icon: 'Palette' },
          { id: 'business', label: 'Business', icon: 'Briefcase' },
          { id: 'social-sciences', label: 'Social Sciences', icon: 'Users' },
          { id: 'health', label: 'Health Sciences', icon: 'Heart' },
          { id: 'law', label: 'Law', icon: 'Scale' },
          { id: 'education', label: 'Education', icon: 'BookOpen' },
          { id: 'engineering', label: 'Engineering', icon: 'Cog' },
        ],
      },
      {
        id: 'campus-life',
        title: 'What interests you about campus life?',
        subtitle: 'Beyond the classroom',
        icon: 'Home',
        selectionType: 'multi',
        options: [
          { id: 'sports', label: 'Sports & Athletics', icon: 'Trophy' },
          { id: 'clubs', label: 'Clubs & Organizations', icon: 'Users' },
          { id: 'arts', label: 'Arts & Culture', icon: 'Music' },
          { id: 'volunteer', label: 'Volunteer Work', icon: 'Heart' },
          { id: 'research', label: 'Research', icon: 'Microscope' },
          { id: 'internships', label: 'Internships', icon: 'Briefcase' },
        ],
      },
    ],
  },

  // HEALTHCARE - HOSPITAL
  'healthcare-hospital': {
    name: 'Hospital',
    category: 'Healthcare',
    defaultTagline: 'Caring for Your Health',
    defaultPrimaryColor: '#10b981',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800',
      'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800',
      'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800',
      'https://images.unsplash.com/photo-1504813184591-01572f98c85f?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'patient-type',
        title: 'How can we help you today?',
        subtitle: 'Select your reason for visiting',
        icon: 'HeartPulse',
        selectionType: 'single',
        options: [
          { id: 'new-patient', label: 'New Patient', icon: 'UserPlus' },
          { id: 'existing-patient', label: 'Existing Patient', icon: 'User' },
          { id: 'emergency', label: 'Emergency', icon: 'AlertTriangle' },
          { id: 'visitor', label: 'Visitor', icon: 'Users' },
        ],
      },
      {
        id: 'services',
        title: 'What services are you interested in?',
        subtitle: 'Select all that apply',
        icon: 'Stethoscope',
        selectionType: 'multi',
        options: [
          { id: 'primary-care', label: 'Primary Care', icon: 'HeartPulse' },
          { id: 'specialty-care', label: 'Specialty Care', icon: 'Microscope' },
          { id: 'imaging', label: 'Imaging & Radiology', icon: 'ScanLine' },
          { id: 'lab', label: 'Lab Services', icon: 'TestTube' },
          { id: 'surgery', label: 'Surgery', icon: 'Scissors' },
          { id: 'emergency', label: 'Emergency Care', icon: 'Siren' },
        ],
      },
      {
        id: 'preferences',
        title: 'Your care preferences?',
        subtitle: 'Help us serve you better',
        icon: 'Settings',
        selectionType: 'multi',
        options: [
          { id: 'telehealth', label: 'Telehealth', icon: 'Video' },
          { id: 'in-person', label: 'In-Person Visits', icon: 'User' },
          { id: 'same-day', label: 'Same-Day Appointments', icon: 'Clock' },
          { id: 'specialist', label: 'Specialist Referrals', icon: 'UserCheck' },
          { id: 'preventive', label: 'Preventive Care', icon: 'Shield' },
          { id: 'chronic-care', label: 'Chronic Care Management', icon: 'HeartPulse' },
        ],
      },
    ],
  },

  // HEALTHCARE - PHARMACY
  'healthcare-pharmacy': {
    name: 'Pharmacy',
    category: 'Healthcare',
    defaultTagline: 'Your Health Partner',
    defaultPrimaryColor: '#14b8a6',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800',
      'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800',
      'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800',
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'pharmacy-needs',
        title: 'What brings you here?',
        subtitle: 'Select your pharmacy needs',
        icon: 'Pill',
        selectionType: 'multi',
        options: [
          { id: 'prescriptions', label: 'Prescriptions', icon: 'FileText' },
          { id: 'refills', label: 'Refills', icon: 'RefreshCw' },
          { id: 'otc', label: 'Over-the-Counter', icon: 'ShoppingBag' },
          { id: 'vitamins', label: 'Vitamins & Supplements', icon: 'Apple' },
          { id: 'consultation', label: 'Pharmacist Consultation', icon: 'MessageCircle' },
          { id: 'vaccines', label: 'Vaccines & Immunizations', icon: 'Syringe' },
        ],
      },
      {
        id: 'services',
        title: 'Interested in these services?',
        subtitle: 'We offer more than prescriptions',
        icon: 'Heart',
        selectionType: 'multi',
        options: [
          { id: 'delivery', label: 'Home Delivery', icon: 'Truck' },
          { id: 'auto-refill', label: 'Auto-Refill', icon: 'Repeat' },
          { id: 'sync', label: 'Med Sync', icon: 'Calendar' },
          { id: 'savings', label: 'Savings Programs', icon: 'Tag' },
          { id: 'health-screening', label: 'Health Screenings', icon: 'Activity' },
          { id: 'medication-review', label: 'Medication Review', icon: 'ClipboardList' },
        ],
      },
      {
        id: 'health-goals',
        title: 'Your health goals?',
        subtitle: 'How can we support you?',
        icon: 'Target',
        selectionType: 'multi',
        options: [
          { id: 'chronic-management', label: 'Manage Chronic Condition', icon: 'HeartPulse' },
          { id: 'wellness', label: 'General Wellness', icon: 'Smile' },
          { id: 'weight', label: 'Weight Management', icon: 'Scale' },
          { id: 'quit-smoking', label: 'Quit Smoking', icon: 'Ban' },
          { id: 'sleep', label: 'Better Sleep', icon: 'Moon' },
          { id: 'immunity', label: 'Boost Immunity', icon: 'Shield' },
        ],
      },
    ],
  },

  // REAL ESTATE - RESIDENTIAL
  'real-estate-residential': {
    name: 'Real Estate - Residential',
    category: 'Real Estate',
    defaultTagline: 'Find Your Dream Home',
    defaultPrimaryColor: '#0369a1',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
      'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'intent',
        title: 'What are you looking to do?',
        subtitle: 'Your real estate goals',
        icon: 'Home',
        selectionType: 'single',
        options: [
          { id: 'buy', label: 'Buy a Home', icon: 'ShoppingCart' },
          { id: 'sell', label: 'Sell My Home', icon: 'DollarSign' },
          { id: 'rent', label: 'Rent', icon: 'Key' },
          { id: 'invest', label: 'Invest', icon: 'TrendingUp' },
        ],
      },
      {
        id: 'property-type',
        title: 'What type of property?',
        subtitle: 'Select all you\'re interested in',
        icon: 'Building',
        selectionType: 'multi',
        options: [
          { id: 'single-family', label: 'Single Family Home', icon: 'Home' },
          { id: 'condo', label: 'Condo', icon: 'Building' },
          { id: 'townhouse', label: 'Townhouse', icon: 'Building2' },
          { id: 'apartment', label: 'Apartment', icon: 'Building' },
          { id: 'land', label: 'Land', icon: 'Trees' },
          { id: 'multi-family', label: 'Multi-Family', icon: 'Home' },
        ],
      },
      {
        id: 'priorities',
        title: 'What matters most to you?',
        subtitle: 'Your priorities',
        icon: 'Star',
        selectionType: 'multi',
        options: [
          { id: 'location', label: 'Location', icon: 'MapPin' },
          { id: 'price', label: 'Price', icon: 'DollarSign' },
          { id: 'size', label: 'Size', icon: 'Maximize' },
          { id: 'schools', label: 'School District', icon: 'GraduationCap' },
          { id: 'amenities', label: 'Amenities', icon: 'Sparkles' },
          { id: 'commute', label: 'Commute', icon: 'Car' },
        ],
      },
    ],
  },

  // REAL ESTATE - COMMERCIAL
  'real-estate-commercial': {
    name: 'Real Estate - Commercial',
    category: 'Real Estate',
    defaultTagline: 'Grow Your Business',
    defaultPrimaryColor: '#475569',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'business-type',
        title: 'What type of business?',
        subtitle: 'Tell us about your company',
        icon: 'Briefcase',
        selectionType: 'single',
        options: [
          { id: 'startup', label: 'Startup', icon: 'Rocket' },
          { id: 'small-business', label: 'Small Business', icon: 'Store' },
          { id: 'enterprise', label: 'Enterprise', icon: 'Building2' },
          { id: 'investor', label: 'Investor', icon: 'TrendingUp' },
        ],
      },
      {
        id: 'space-type',
        title: 'What type of space?',
        subtitle: 'Select all that apply',
        icon: 'Building',
        selectionType: 'multi',
        options: [
          { id: 'office', label: 'Office Space', icon: 'Briefcase' },
          { id: 'retail', label: 'Retail Space', icon: 'ShoppingBag' },
          { id: 'warehouse', label: 'Warehouse', icon: 'Package' },
          { id: 'industrial', label: 'Industrial', icon: 'Factory' },
          { id: 'restaurant', label: 'Restaurant', icon: 'UtensilsCrossed' },
          { id: 'mixed-use', label: 'Mixed-Use', icon: 'Building2' },
        ],
      },
      {
        id: 'requirements',
        title: 'Key requirements?',
        subtitle: 'What do you need?',
        icon: 'CheckSquare',
        selectionType: 'multi',
        options: [
          { id: 'location', label: 'Prime Location', icon: 'MapPin' },
          { id: 'parking', label: 'Parking', icon: 'Car' },
          { id: 'signage', label: 'Signage Opportunities', icon: 'Eye' },
          { id: 'move-in-ready', label: 'Move-In Ready', icon: 'CheckCircle' },
          { id: 'customizable', label: 'Customizable Space', icon: 'Wrench' },
          { id: 'tech-infrastructure', label: 'Tech Infrastructure', icon: 'Wifi' },
        ],
      },
    ],
  },

  // AUTOMOTIVE - DEALERSHIP
  'automotive-dealership': {
    name: 'Auto Dealership',
    category: 'Automotive',
    defaultTagline: 'Drive Your Dream',
    defaultPrimaryColor: '#dc2626',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'shopping-type',
        title: 'What are you looking for?',
        subtitle: 'Your car shopping goal',
        icon: 'Car',
        selectionType: 'single',
        options: [
          { id: 'new', label: 'New Car', icon: 'Sparkles' },
          { id: 'used', label: 'Used Car', icon: 'Car' },
          { id: 'lease', label: 'Lease', icon: 'FileText' },
          { id: 'trade-in', label: 'Trade-In', icon: 'RefreshCw' },
        ],
      },
      {
        id: 'vehicle-type',
        title: 'What type of vehicle?',
        subtitle: 'Select all you\'re interested in',
        icon: 'CarFront',
        selectionType: 'multi',
        options: [
          { id: 'sedan', label: 'Sedan', icon: 'Car' },
          { id: 'suv', label: 'SUV', icon: 'Truck' },
          { id: 'truck', label: 'Truck', icon: 'Truck' },
          { id: 'sports', label: 'Sports Car', icon: 'Zap' },
          { id: 'electric', label: 'Electric', icon: 'BatteryCharging' },
          { id: 'hybrid', label: 'Hybrid', icon: 'Leaf' },
        ],
      },
      {
        id: 'priorities',
        title: 'What matters most?',
        subtitle: 'Your priorities',
        icon: 'Star',
        selectionType: 'multi',
        options: [
          { id: 'price', label: 'Best Price', icon: 'DollarSign' },
          { id: 'fuel-efficiency', label: 'Fuel Efficiency', icon: 'Droplet' },
          { id: 'safety', label: 'Safety Features', icon: 'Shield' },
          { id: 'technology', label: 'Technology', icon: 'Smartphone' },
          { id: 'cargo-space', label: 'Cargo Space', icon: 'Package' },
          { id: 'performance', label: 'Performance', icon: 'Gauge' },
        ],
      },
    ],
  },

  // AUTOMOTIVE - SERVICE
  'automotive-service': {
    name: 'Auto Service & Repair',
    category: 'Automotive',
    defaultTagline: 'Keep You Moving',
    defaultPrimaryColor: '#ea580c',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800',
      'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800',
      'https://images.unsplash.com/photo-1632823469149-62c825ce2906?w=800',
      'https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'vehicle-info',
        title: 'What type of vehicle do you have?',
        subtitle: 'Help us prepare for your service',
        icon: 'Car',
        selectionType: 'single',
        options: [
          { id: 'sedan', label: 'Sedan', icon: 'Car' },
          { id: 'suv', label: 'SUV', icon: 'Truck' },
          { id: 'truck', label: 'Truck', icon: 'Truck' },
          { id: 'van', label: 'Van', icon: 'Bus' },
          { id: 'sports', label: 'Sports Car', icon: 'Zap' },
          { id: 'electric', label: 'Electric', icon: 'BatteryCharging' },
        ],
      },
      {
        id: 'services-needed',
        title: 'What services do you need?',
        subtitle: 'Select all that apply',
        icon: 'Wrench',
        selectionType: 'multi',
        options: [
          { id: 'oil-change', label: 'Oil Change', icon: 'Droplet' },
          { id: 'brake-service', label: 'Brake Service', icon: 'CircleStop' },
          { id: 'tire-service', label: 'Tire Service', icon: 'Circle' },
          { id: 'inspection', label: 'Inspection', icon: 'Search' },
          { id: 'battery', label: 'Battery Service', icon: 'Battery' },
          { id: 'engine', label: 'Engine Repair', icon: 'Cog' },
          { id: 'transmission', label: 'Transmission', icon: 'Settings' },
          { id: 'ac-service', label: 'A/C Service', icon: 'Wind' },
        ],
      },
      {
        id: 'preferences',
        title: 'Service preferences?',
        subtitle: 'How can we serve you best?',
        icon: 'Star',
        selectionType: 'multi',
        options: [
          { id: 'same-day', label: 'Same-Day Service', icon: 'Clock' },
          { id: 'drop-off', label: 'Drop-Off', icon: 'MapPin' },
          { id: 'waiting', label: 'While You Wait', icon: 'Hourglass' },
          { id: 'shuttle', label: 'Shuttle Service', icon: 'Bus' },
          { id: 'loaner', label: 'Loaner Vehicle', icon: 'Car' },
          { id: 'mobile', label: 'Mobile Service', icon: 'Truck' },
        ],
      },
    ],
  },

  // ENTERTAINMENT - STREAMING
  'entertainment-streaming': {
    name: 'Streaming Service',
    category: 'Entertainment',
    defaultTagline: 'Stream Your World',
    defaultPrimaryColor: '#e11d48',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800',
      'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=800',
      'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=800',
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'content-preference',
        title: 'What do you love to watch?',
        subtitle: 'Select all that apply',
        icon: 'Film',
        selectionType: 'multi',
        options: [
          { id: 'movies', label: 'Movies', icon: 'Film' },
          { id: 'tv-shows', label: 'TV Shows', icon: 'Tv' },
          { id: 'documentaries', label: 'Documentaries', icon: 'FileVideo' },
          { id: 'anime', label: 'Anime', icon: 'Sparkles' },
          { id: 'kids', label: 'Kids & Family', icon: 'Baby' },
          { id: 'sports', label: 'Sports', icon: 'Trophy' },
        ],
      },
      {
        id: 'genres',
        title: 'Favorite genres?',
        subtitle: 'Pick your top choices',
        icon: 'Star',
        selectionType: 'multi',
        options: [
          { id: 'action', label: 'Action', icon: 'Zap' },
          { id: 'comedy', label: 'Comedy', icon: 'Laugh' },
          { id: 'drama', label: 'Drama', icon: 'Heart' },
          { id: 'thriller', label: 'Thriller', icon: 'AlertTriangle' },
          { id: 'sci-fi', label: 'Sci-Fi', icon: 'Rocket' },
          { id: 'romance', label: 'Romance', icon: 'HeartHandshake' },
          { id: 'horror', label: 'Horror', icon: 'Ghost' },
          { id: 'fantasy', label: 'Fantasy', icon: 'Wand' },
        ],
      },
      {
        id: 'watching-habits',
        title: 'How do you watch?',
        subtitle: 'Your viewing style',
        icon: 'Eye',
        selectionType: 'multi',
        options: [
          { id: 'binge', label: 'Binge Watching', icon: 'FastForward' },
          { id: 'weekly', label: 'Weekly Episodes', icon: 'Calendar' },
          { id: 'family', label: 'Family Viewing', icon: 'Users' },
          { id: 'solo', label: 'Solo Watching', icon: 'User' },
          { id: 'background', label: 'Background Noise', icon: 'Volume2' },
          { id: 'movie-nights', label: 'Movie Nights', icon: 'Moon' },
        ],
      },
    ],
  },

  // ENTERTAINMENT - GAMING
  'entertainment-gaming': {
    name: 'Gaming Platform',
    category: 'Entertainment',
    defaultTagline: 'Level Up Your Game',
    defaultPrimaryColor: '#7c3aed',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800',
      'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=800',
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800',
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'platform',
        title: 'What platforms do you play on?',
        subtitle: 'Select all that apply',
        icon: 'Gamepad2',
        selectionType: 'multi',
        options: [
          { id: 'pc', label: 'PC', icon: 'Monitor' },
          { id: 'playstation', label: 'PlayStation', icon: 'Gamepad' },
          { id: 'xbox', label: 'Xbox', icon: 'Gamepad2' },
          { id: 'nintendo', label: 'Nintendo', icon: 'Gamepad' },
          { id: 'mobile', label: 'Mobile', icon: 'Smartphone' },
          { id: 'vr', label: 'VR', icon: 'Glasses' },
        ],
      },
      {
        id: 'game-types',
        title: 'What games do you play?',
        subtitle: 'Pick your favorites',
        icon: 'Joystick',
        selectionType: 'multi',
        options: [
          { id: 'fps', label: 'FPS', icon: 'Target' },
          { id: 'rpg', label: 'RPG', icon: 'Swords' },
          { id: 'strategy', label: 'Strategy', icon: 'Brain' },
          { id: 'sports', label: 'Sports', icon: 'Trophy' },
          { id: 'racing', label: 'Racing', icon: 'Flag' },
          { id: 'adventure', label: 'Adventure', icon: 'Map' },
          { id: 'puzzle', label: 'Puzzle', icon: 'Puzzle' },
          { id: 'mmo', label: 'MMO', icon: 'Users' },
        ],
      },
      {
        id: 'play-style',
        title: 'How do you like to play?',
        subtitle: 'Your gaming style',
        icon: 'Zap',
        selectionType: 'multi',
        options: [
          { id: 'solo', label: 'Solo Campaign', icon: 'User' },
          { id: 'multiplayer', label: 'Multiplayer', icon: 'Users' },
          { id: 'competitive', label: 'Competitive', icon: 'Award' },
          { id: 'casual', label: 'Casual', icon: 'Smile' },
          { id: 'story-driven', label: 'Story-Driven', icon: 'BookOpen' },
          { id: 'cooperative', label: 'Co-op', icon: 'Handshake' },
        ],
      },
    ],
  },

  // FINANCE - BANK
  'finance-bank': {
    name: 'Bank',
    category: 'Finance',
    defaultTagline: 'Banking Made Simple',
    defaultPrimaryColor: '#059669',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=800',
      'https://images.unsplash.com/photo-1556742393-d75f468bfcb0?w=800',
      'https://images.unsplash.com/photo-1579621970588-a35d0e7ab9b6?w=800',
      'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'banking-needs',
        title: 'What banking services do you need?',
        subtitle: 'Select all that interest you',
        icon: 'Building',
        selectionType: 'multi',
        options: [
          { id: 'checking', label: 'Checking Account', icon: 'CreditCard' },
          { id: 'savings', label: 'Savings Account', icon: 'PiggyBank' },
          { id: 'credit-card', label: 'Credit Card', icon: 'CreditCard' },
          { id: 'loans', label: 'Loans', icon: 'DollarSign' },
          { id: 'mortgage', label: 'Mortgage', icon: 'Home' },
          { id: 'investment', label: 'Investment', icon: 'TrendingUp' },
        ],
      },
      {
        id: 'banking-style',
        title: 'How do you prefer to bank?',
        subtitle: 'Your banking preferences',
        icon: 'Smartphone',
        selectionType: 'multi',
        options: [
          { id: 'mobile', label: 'Mobile App', icon: 'Smartphone' },
          { id: 'online', label: 'Online Banking', icon: 'Monitor' },
          { id: 'branch', label: 'In-Branch', icon: 'Building' },
          { id: 'atm', label: 'ATM', icon: 'Square' },
          { id: 'phone', label: 'Phone Banking', icon: 'Phone' },
        ],
      },
      {
        id: 'financial-goals',
        title: 'What are your financial goals?',
        subtitle: 'We can help you achieve them',
        icon: 'Target',
        selectionType: 'multi',
        options: [
          { id: 'save-money', label: 'Save Money', icon: 'PiggyBank' },
          { id: 'build-credit', label: 'Build Credit', icon: 'TrendingUp' },
          { id: 'buy-home', label: 'Buy a Home', icon: 'Home' },
          { id: 'invest', label: 'Invest', icon: 'LineChart' },
          { id: 'retire', label: 'Plan for Retirement', icon: 'Sunset' },
          { id: 'education', label: 'Education Savings', icon: 'GraduationCap' },
        ],
      },
    ],
  },

  // FINANCE - INVESTMENT
  'finance-investment': {
    name: 'Investment Platform',
    category: 'Finance',
    defaultTagline: 'Invest in Your Future',
    defaultPrimaryColor: '#16a34a',
    defaultSecondaryColor: '#ffffff',
    heroImageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
    bannerImages: [
      'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
      'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800',
      'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800',
      'https://images.unsplash.com/photo-1468254095679-bbcba94a7066?w=800',
    ],
    onboardingQuestions: [
      {
        id: 'experience-level',
        title: 'Investment experience?',
        subtitle: 'Tell us about your background',
        icon: 'TrendingUp',
        selectionType: 'single',
        options: [
          { id: 'beginner', label: 'Beginner', icon: 'Sprout' },
          { id: 'intermediate', label: 'Intermediate', icon: 'BarChart' },
          { id: 'advanced', label: 'Advanced', icon: 'LineChart' },
          { id: 'expert', label: 'Expert', icon: 'Trophy' },
        ],
      },
      {
        id: 'investment-types',
        title: 'What interests you?',
        subtitle: 'Select investment types',
        icon: 'PieChart',
        selectionType: 'multi',
        options: [
          { id: 'stocks', label: 'Stocks', icon: 'TrendingUp' },
          { id: 'etfs', label: 'ETFs', icon: 'BarChart3' },
          { id: 'bonds', label: 'Bonds', icon: 'Receipt' },
          { id: 'crypto', label: 'Cryptocurrency', icon: 'Bitcoin' },
          { id: 'real-estate', label: 'Real Estate', icon: 'Home' },
          { id: 'commodities', label: 'Commodities', icon: 'Package' },
        ],
      },
      {
        id: 'goals',
        title: 'Your investment goals?',
        subtitle: 'What are you investing for?',
        icon: 'Target',
        selectionType: 'multi',
        options: [
          { id: 'retirement', label: 'Retirement', icon: 'Sunset' },
          { id: 'wealth-building', label: 'Wealth Building', icon: 'TrendingUp' },
          { id: 'passive-income', label: 'Passive Income', icon: 'DollarSign' },
          { id: 'short-term', label: 'Short-Term Gains', icon: 'Zap' },
          { id: 'education', label: 'Education Fund', icon: 'GraduationCap' },
          { id: 'emergency-fund', label: 'Emergency Fund', icon: 'Shield' },
        ],
      },
    ],
  },

  // Add more verticals as needed...
};

export const DEFAULT_BRAND_KIT: BrandKitConfig = {
  brandName: 'The Home Depot',
  tagline: 'DO-ER',
  primaryColor: '#f97316',
  secondaryColor: '#ffffff',
  logoUrl: 'https://pbs.twimg.com/profile_images/1734959351842865152/bQYbcgqP_400x400.jpg',
  vertical: 'retail-home-improvement',
};
